// <auto-generated />
namespace JBCSite.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Role_RolePermissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_RolePermissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201905210255307_Role_RolePermissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
